query MediaItemsQuery($title: String!, $limit: Int, $autoCorrect: Boolean) {
  movies(title: $title, limit: $limit, autoCorrect: $autoCorrect) {
    SubdlId
    title
    year
    posterPath
    mediaType
  }
}
